#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'train-control','console_scripts','esp32_wifi'
__requires__ = 'train-control'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('train-control', 'console_scripts', 'esp32_wifi')()
    )
